name: Gradle Build

on: 
  push:
    branches:
    - master
  pull_requests:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - users: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: ./gradlew test

      